stages:
  - deploy_api
  - build_service_dev
  - build_web_dev


job1:
  stage: deploy_api
  script:
    - cd ./hrm-server
    - mvn clean deploy -f pom-biz-facade.xml -e
  only:
    - tags
  tags:
    - mavenrunner01

job2-1:
  stage: build_service_dev
  script:
    - mvn clean package -f  ./hrm-server/pom-biz-service-server.xml
    - docker login --username=$DOCKER_USER ccr.ccs.tencentyun.com  -p Lesso2128
    - docker build -t ccr.ccs.tencentyun.com/samanea/hrmservice_dev:$CI_COMMIT_TAG ./ -f ./dockerfile_service
    - docker push ccr.ccs.tencentyun.com/samanea/hrmservice_dev:$CI_COMMIT_TAG
    - docker rmi ccr.ccs.tencentyun.com/samanea/hrmservice_dev:$CI_COMMIT_TAG
  only:
    - /^qas-.*$/
  tags:
    - mavenrunner02

job2-2:
  stage: build_web_dev
  script:
    - mvn clean package -f ./hrm-server/pom-biz-web-server.xml
    - docker login --username=$DOCKER_USER ccr.ccs.tencentyun.com  -p Lesso2128
    - docker build -t ccr.ccs.tencentyun.com/samanea/hrmweb_dev:$CI_COMMIT_TAG ./ -f ./dockerfile_web
    - docker push ccr.ccs.tencentyun.com/samanea/hrmweb_dev:$CI_COMMIT_TAG
    - docker rmi ccr.ccs.tencentyun.com/samanea/hrmweb_dev:$CI_COMMIT_TAG
  only:
    - /^qas-.*$/
  tags:
    - mavenrunner03

